	$(".campositionsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".campositionsensor").click(function(){
		$(this).toggleClass("red");
	});	
	$(".camshaft").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".camshaft").click(function(){
		$(this).toggleClass("red");
	});		
	$(".clutchpilotbearing").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".clutchpilotbearing").click(function(){
		$(this).toggleClass("red");
	});		
	$(".coilpack1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".coilpack1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".coilpack2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".coilpack2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".coolanttempsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".coolanttempsensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing3").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing3").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing4").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing4").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing5").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing5").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankshaft").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankshaft").click(function(){
		$(this).toggleClass("red");
	});		
	$(".engineblock").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".engineblock").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustpushrods1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustpushrods1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustpushrods2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustpushrods2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustrockers1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustrockers1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustrockers2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustrockers2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustvalves1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustvalves1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustvalves2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustvalves2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".fuelrail").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".fuelrail").click(function(){
		$(this).toggleClass("red");
	});		
	$(".head1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".head1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".head2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".head2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakemanifold").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakemanifold").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakepushrods1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakepushrods1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakepushrods2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakepushrods2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakerockers1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakerockers1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakerockers2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakerockers2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakevalves1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakevalves1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakevalves2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakevalves2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".knocksensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".knocksensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap3").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap3").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap4").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap4").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap5").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap5").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing3").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing3").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing4").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing4").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing5").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing5").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mapsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mapsensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oilfillerneck").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oilfillerneck").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oillevelsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oillevelsensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oilpan").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oilpan").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oilpressuresensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oilpressuresensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oiltempsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oiltempsensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston3").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston3").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston4").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston4").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston5").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston5").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston6").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston6").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston7").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston7").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston8").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston8").click(function(){
		$(this).toggleClass("red");
	});		
	$(".pushrodexhaustbank1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".pushrodexhaustbank1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".pushrodexhaustbank2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".pushrodexhaustbank2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".pushrodintakebank1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".pushrodintakebank1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".pushrodintakebank2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".pushrodintakebank2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".steamtube").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".steamtube").click(function(){
		$(this).toggleClass("red");
	});	
	$(".timingchain").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".timingchain").click(function(){
		$(this).toggleClass("red");
	});		
	$(".throttlebody").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".throttlebody").click(function(){
		$(this).toggleClass("red");
	});		
	$(".valleycover").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".valleycover").click(function(){
		$(this).toggleClass("red");
	});		
	$(".valvecover1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".valvecover1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".valvecover2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".valvecover2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".windagetray").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".windagetray").click(function(){
		$(this).toggleClass("red");
	});		
	$("td").mouseleave(function(){
	$("[class='grey']").removeClass("grey");
	});
	$(".accompressor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".accompressor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".alternator").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".alternator").click(function(){
		$(this).toggleClass("red");
	});	
	$(".battery").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".battery").click(function(){
		$(this).toggleClass("red");
	});		
	$(".bbumper").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".bbumper").click(function(){
		$(this).toggleClass("red");
	});		
	$(".blaxle").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".blaxle").click(function(){
		$(this).toggleClass("red");
	});		
	$(".blcaliper").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".blcaliper").click(function(){
		$(this).toggleClass("red");
	});		
	$(".blcarrier").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".blcarrier").click(function(){
		$(this).toggleClass("red");
	});		
	$(".blcoilspring").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".blcoilspring").click(function(){
		$(this).toggleClass("red");
	});		
	$(".blrotor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".blrotor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".blshock").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".blshock").click(function(){
		$(this).toggleClass("red");
	});		
	$(".bltire").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".bltire").click(function(){
		$(this).toggleClass("red");
	});		
	$(".blwheel").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".blwheel").click(function(){
		$(this).toggleClass("red");
	});		
	$(".brakemastercylinder").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".brakemastercylinder").click(function(){
		$(this).toggleClass("red");
	});		
	$(".braxle").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".braxle").click(function(){
		$(this).toggleClass("red");
	});		
	$(".brcaliper").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".brcaliper").click(function(){
		$(this).toggleClass("red");
	});		
	$(".brcarrier").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".brcarrier").click(function(){
		$(this).toggleClass("red");
	});		
	$(".brcoilspring").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".brcoilspring").click(function(){
		$(this).toggleClass("red");
	});		
	$(".brrotor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".brrotor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".brshock").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".brshock").click(function(){
		$(this).toggleClass("red");
	});		
	$(".brtire").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".brtire").click(function(){
		$(this).toggleClass("red");
	});		
	$(".brwheel").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".brwheel").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crossmember").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crossmember").click(function(){
		$(this).toggleClass("red");
	});		
	$(".differential").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".differential").click(function(){
		$(this).toggleClass("red");
	});		
	$(".driveline").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".driveline").click(function(){
		$(this).toggleClass("red");
	});		
	$(".engine").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".engine").click(function(){
		$(this).toggleClass("red");
	});		
	$(".fbumper").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".fbumper").click(function(){
		$(this).toggleClass("red");
	});		
	$(".flcaliper").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".flcaliper").click(function(){
		$(this).toggleClass("red");
	});		
	$(".flcarrier").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".flcarrier").click(function(){
		$(this).toggleClass("red");
	});		
	$(".flheadlamp").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".flheadlamp").click(function(){
		$(this).toggleClass("red");
	});		
	$(".flhub").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".flhub").click(function(){
		$(this).toggleClass("red");
	});		
	$(".fllowercontrolarm").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".fllowercontrolarm").click(function(){
		$(this).toggleClass("red");
	});		
	$(".flrotor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".flrotor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".flshock").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".flshock").click(function(){
		$(this).toggleClass("red");
	});		
	$(".flspindle").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".flspindle").click(function(){
		$(this).toggleClass("red");
	});		
	$(".fltire").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".fltire").click(function(){
		$(this).toggleClass("red");
	});		
	$(".fluppercontrolarm").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".fluppercontrolarm").click(function(){
		$(this).toggleClass("red");
	});		
	$(".flwheel").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".flwheel").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frcaliper").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frcaliper").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frcarrier").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frcarrier").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frheadlamp").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frheadlamp").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frhub").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frhub").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frlowercontrolarm").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frlowercontrolarm").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frontsway").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frontsway").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frrotor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frrotor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frshock").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frshock").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frspindle").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frspindle").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frtire").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frtire").click(function(){
		$(this).toggleClass("red");
	});		
	$(".fruppercontrolarm").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".fruppercontrolarm").click(function(){
		$(this).toggleClass("red");
	});		
	$(".frwheel").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".frwheel").click(function(){
		$(this).toggleClass("red");
	});		
	$(".gastank").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".gastank").click(function(){
		$(this).toggleClass("red");
	});		
	$(".hood").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".hood").click(function(){
		$(this).toggleClass("red");
	});		
	$(".lcat").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".lcat").click(function(){
		$(this).toggleClass("red");
	});		
	$(".ldoor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".ldoor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".lexhaustmanifold").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".lexhaustmanifold").click(function(){
		$(this).toggleClass("red");
	});		
	$(".lfender").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".lfender").click(function(){
		$(this).toggleClass("red");
	});		
	$(".lkicker").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".lkicker").click(function(){
		$(this).toggleClass("red");
	});		
	$(".lmirror").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".lmirror").click(function(){
		$(this).toggleClass("red");
	});		
	$(".lquarter").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".lquarter").click(function(){
		$(this).toggleClass("red");
	});		
	$(".ltaillight").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".ltaillight").click(function(){
		$(this).toggleClass("red");
	});		
	$(".lttop").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".lttop").click(function(){
		$(this).toggleClass("red");
	});		
	$(".lwindow").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".lwindow").click(function(){
		$(this).toggleClass("red");
	});		
	$(".muffler").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".muffler").click(function(){
		$(this).toggleClass("red");
	});		
	$(".panhardbar").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".panhardbar").click(function(){
		$(this).toggleClass("red");
	});		
	$(".panhardsupport").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".panhardsupport").click(function(){
		$(this).toggleClass("red");
	});		
	$(".powersteeringpump").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".powersteeringpump").click(function(){
		$(this).toggleClass("red");
	});		
	$(".radiator").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".radiator").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rcat").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rcat").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rdoor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rdoor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rearsway").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rearsway").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rexhaustmanifold").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rexhaustmanifold").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rfender").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rfender").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rkicker").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rkicker").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rmirror").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rmirror").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rquarter").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rquarter").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rtaillight").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rtaillight").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rttop").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rttop").click(function(){
		$(this).toggleClass("red");
	});		
	$(".rwindow").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".rwindow").click(function(){
		$(this).toggleClass("red");
	});		
	$(".spoiler").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".spoiler").click(function(){
		$(this).toggleClass("red");
	});		
	$(".steeringrack").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".steeringrack").click(function(){
		$(this).toggleClass("red");
	});		
	$(".tailpanel").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".tailpanel").click(function(){
		$(this).toggleClass("red");
	});		
	$(".torquearm").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".torquearm").click(function(){
		$(this).toggleClass("red");
	});		
	$(".transmission").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".transmission").click(function(){
		$(this).toggleClass("red");
	});		
	$(".waterpump").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".waterpump").click(function(){
		$(this).toggleClass("red");
	});		
	$(".ypipe").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".ypipe").click(function(){
		$(this).toggleClass("red");
	});		