<script src="jquery-3.3.1.min.js"></script>
<script>

$(document).ready(function(){
	$(".campositionsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".campositionsensor").click(function(){
		$(this).toggleClass("red");
	});	
		
	$(".camshaft").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".camshaft").click(function(){
		$(this).toggleClass("red");
	});		
	$(".clutchpilotbearing").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".clutchpilotbearing").click(function(){
		$(this).toggleClass("red");
	});		
	$(".coilpack1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".coilpack1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".coilpack2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".coilpack2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".coolanttempsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".coolanttempsensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing3").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing3").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing4").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing4").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankbearing5").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankbearing5").click(function(){
		$(this).toggleClass("red");
	});		
	$(".crankshaft").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".crankshaft").click(function(){
		$(this).toggleClass("red");
	});		
	$(".engineblock").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".engineblock").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustpushrods1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustpushrods1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustpushrods2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustpushrods2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustrockers1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustrockers1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustrockers2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustrockers2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustvalves1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustvalves1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".exhaustvalves2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".exhaustvalves2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".fuelrail").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".fuelrail").click(function(){
		$(this).toggleClass("red");
	});		
	$(".head1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".head1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".head2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".head2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakemanifold").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakemanifold").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakepushrods1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakepushrods1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakepushrods2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakepushrods2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakerockers1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakerockers1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakerockers2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakerockers2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakevalves1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakevalves1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".intakevalves2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".intakevalves2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".knocksensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".knocksensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap3").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap3").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap4").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap4").click(function(){
		$(this).toggleClass("red");
	});		
	$(".maincap5").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".maincap5").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing3").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing3").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing4").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing4").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mainbearing5").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mainbearing5").click(function(){
		$(this).toggleClass("red");
	});		
	$(".mapsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".mapsensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oilfillerneck").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oilfillerneck").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oillevelsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oillevelsensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oilpan").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oilpan").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oilpressuresensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oilpressuresensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".oiltempsensor").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".oiltempsensor").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston3").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston3").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston4").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston4").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston5").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston5").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston6").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston6").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston7").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston7").click(function(){
		$(this).toggleClass("red");
	});		
	$(".piston8").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".piston8").click(function(){
		$(this).toggleClass("red");
	});		
	$(".pushrodexhaustbank1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".pushrodexhaustbank1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".pushrodexhaustbank2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".pushrodexhaustbank2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".pushrodintakebank1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".pushrodintakebank1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".pushrodintakebank2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".pushrodintakebank2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".steamtube").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".steamtube").click(function(){
		$(this).toggleClass("red");
	});	
	$(".timingchain").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".timingchain").click(function(){
		$(this).toggleClass("red");
	});		
	$(".throttlebody").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".throttlebody").click(function(){
		$(this).toggleClass("red");
	});		
	$(".valleycover").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".valleycover").click(function(){
		$(this).toggleClass("red");
	});		
	$(".valvecover1").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".valvecover1").click(function(){
		$(this).toggleClass("red");
	});		
	$(".valvecover2").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".valvecover2").click(function(){
		$(this).toggleClass("red");
	});		
	$(".windagetray").hover(function(){
		$(this).toggleClass("grey");
	});
	$(".windagetray").click(function(){
		$(this).toggleClass("red");
	});		
	$("td").mouseleave(function(){
	$("[class='grey']").removeClass("grey");
	});
});
</script>














